name: "[CICD] Build and Deploy to GCP"

on:
  release:
    types: ["published"]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pull-requests: read

concurrency:
  # This prevents concurrency in building/deploying an environment.
  group: release
  cancel-in-progress: true

jobs:
  build_and_deploy:
    name: "build and deploy"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: "Authenticate with Google Cloud"
        id: auth
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker europe-west4-docker.pkg.dev

      - name: Build image
        run: docker build . --tag europe-west4-docker.pkg.dev/solodin-live-466415/solodin-live/solodin-live:latest

      - name: Push image
        run: docker push europe-west4-docker.pkg.dev/solodin-live-466415/solodin-live/solodin-live:latest

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          gcloud_component: beta
          service: solodin-live
          image: europe-west4-docker.pkg.dev/solodin-live-466415/solodin-live/solodin-live:latest
          region: europe-west4
          project_id: solodin-live
          flags: "--min-instances=1 --service-min-instances=1 --allow-unauthenticated"
          # env_vars: |-
          #   DATABASE_URL=${{ secrets.DATABASE_URL }}
          #   NEWSLETTER_ENDPOINT=${{ secrets.NEWSLETTER_ENDPOINT }}
          #   NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
          #   CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }}

      # - name: Check the deployment
      #   uses: wei/wget@v1
      #   with:
      #     args: -O index.html https://db-academy.io/